### ISSUE TITLE
K6 setup() execution timed out after 60 seconds

### ISSUE THREAD

**Issue by Lethanhson9901** [owncloud/cdperf#54]
I ran login test with 100 vus using this command in readme:
```docker run -e BASE_URL=https://cloud-domain.org:80 -e PLATFORM=ownCloudServer -e AUTH_ADAPTER=basicAuth -e ADMIN_LOGIN=main -e ADMIN_PASSWORD=secret --rm -i grafana/k6 run --vus 100 - < artifacts/koko-010-login.js```

But I got this error about K6 timedout:
"level=error msg="setup() execution timed out after 60 seconds" hint="You can increase the time limit via the setupTimeout option"
![image](https://github.com/owncloud/cdperf/assets/49090718/26a5e874-208e-4166-9b65-4b17e9ee9a27)

Could you please fix this with timed out configuration ?

I also try to modified `010-login.ts` file but don't know how to build that TS file in to JS file looks like the file in `artifact` folder.

Thanks!

**Comment by fschade** [comment]
@Lethanhson9901 building should be straight forward:

```
$ pnpm install && pnpm build
```

that updates the artifacts.

Regarding the timeout, you need to have a installation somewhere and then update the urls, e.g. `BASE_URL=https://cloud-domain.org:80`. Let me know if it worked

**Comment by fschade** [comment]
@Lethanhson9901 please reopen if needed
